# Default initial positions for firefighter's ros2_control fake system

initial_positions:
  joint2_to_joint1: 0.0
  joint3_to_joint2: 0.0
  joint4_to_joint3: 0.0
  joint5_to_joint4: 0.0
  joint6_to_joint5: 0.0
  joint6output_to_joint6: 0.0
  # camera_flange_to_needle: 0.0
  # world_to_table: 0.0
  # table_to_base: 0.0
